### PR TITLE
Suggested copy change

### PR DESCRIPTION
**Pull request by mateoclarke**
😃 > 🤖
 
I think our comments should be extra polite since it is a bot and could be seen as spammy by some ppl.

I think the "Abandoned and needs love" label doesn't always work well to described project ideas. We should encourage as many project ideas as possible. The best ones will be the ones that are adopted. _That's the assumption at least._ And the ones that never take off or stall out can just be called "inactive". That's my vote, 🗳

### CODE REVIEW

**Review by amaliebarras — COMMENTED** [review]
Ok with changing the bot copy but inclined to keep the label language the same. @werdnanoslen where did we land on it after he convo at Jo's?

**Comment by werdnanoslen** [comment]
Basically where it is now. No consensus on changing the label, but the
issues I listed above I think are important and unresolved.

**Comment by werdnanoslen** [comment]
@amaliebarras see #247

**Review by werdnanoslen — CHANGES_REQUESTED** [review]
This is kinda two issues in one: changing the message and changing the label. Can you change the label to what it is now (Abandoned) and start a separate issue (or chat on #projects-team?

**Comment by mateoclarke** [comment]
Made the change you requested and the conversation is going on here: https://github.com/open-austin/iced-coffee/issues/247#issuecomment-294170457

**Pull request merged**
